name: geo_tracker_app
description: A professional Flutter geo-tracking application with background location support

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.1.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  workmanager: ^0.9.0+3
  shared_preferences: ^2.2.2
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^19.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true